#!/usr/bin/env zsh

alien_theme(){
  ALIEN_PROMPT_FG=0

  ALIEN_SECTION_EXIT_FG=0
  ALIEN_SECTION_EXIT_BG=87
  ALIEN_SECTION_EXIT_BG_ERROR=202

  ALIEN_SECTION_TIME_FG=0
  ALIEN_SECTION_TIME_BG=193

  ALIEN_SECTION_BATTERY_FG=193
  ALIEN_SECTION_BATTERY_BG=0

  ALIEN_SECTION_USER_FG=0
  ALIEN_SECTION_USER_BG=87

  ALIEN_SECTION_PATH_FG=45
  ALIEN_SECTION_PATH_BG=0

  ALIEN_SECTION_VCS_BRANCH_FG=87
  ALIEN_SECTION_VCS_BRANCH_BG=0
  ALIEN_SECTION_VCS_STATUS_FG=87
  ALIEN_SECTION_VCS_STATUS_BG=238
  ALIEN_SECTION_VCS_DIRTY_FG=87
  ALIEN_SECTION_VCS_DIRTY_BG=238

  ALIEN_SECTION_SSH_FG=238

  ALIEN_SECTION_VENV_FG=238

  PLIB_GIT_TRACKED_COLOR=193
  PLIB_GIT_UNTRACKED_COLOR=87
}
